Nov 29th, 2016
==============

If methodA throws MyException then output is?
---------------------------------------------

```java
public static void main(String[] args) throws MyException {
  try {
    methodA(args);            // Op 1
    System.out.println("B");
  }
  catch (MyException e) {
    e.printStackTrace();
    System.out.println("C");
    throw e;                  // Op 2
  }
  finally {
    System.out.println("D");  // Op 3
  }
  System.out.println("E");    // Op 4
}
```

This sample of code will print "CD". At Op 1 the method call throws an exception of type MyException (skipping "B" print), caught by the `catch` block, printing out "C", throwing another exception at Op 2, therefore the program will never finish (Op 4 will never be executed).

However by definition, the `finally` will always be executed, printing out "D".

The program prints out "CD" overall.

What is the correct output?
---------------------------

```java
public static void main(String[] args) {
  String name = "Fred";
  int num = 100;
  double dNum = 3.14159;
  System.out.printf("Hello %6s\n", name);     // Op 1
  System.out.printf("%05d,%.2f", num, dNum);  // Op 2
}
```

At Op 1, the string was elongated to 6 characters in length (put String in a field with a width of 6), with spaces **prepended**, therefore `name` containing "Fred" will be changed into "Fred  ".

At Op 2, `%05d` elongates the length of `num` into 5 decimals, **prepending** 0s into the variable, then "100" becomes "00100" - as "05d" specifies "leading with zeros"; `%.2f` will specify that the double/float number to print out with a precision of 2 digis after the "dot", therefore "3.14159" becomes "3.14".

Overall, the program will print out:

```
Hello   Fred
00100,3.14
```
